"""Added SiteSetting and Media models

Revision ID: a41cfbdae756
Revises: 3595944d9b43
Create Date: 2026-09-03 12:06:28.951859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a41cfbdae756'
down_revision: Union[str, Sequence[str], None] = '3595944d9b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'status')
    op.drop_column('users', 'service_type')
    op.drop_column('users', 'city')
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('service_type', postgresql.ENUM('Business NTN', 'Simple NTN Registration', 'Business Registration', 'Company Registration', 'Filer Registration', 'GST Registration', 'Tax Return Filing', 'FBR Notices', 'Wealth Statement', 'DTS Registration', 'Imp & Exp License (PSW)', 'Trade Mark Registration', 'PEC Registration', 'Chamber Membership', 'PSEB', 'DNFBP', 'Other', name='servicetype'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
